### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by b-t-k** [gsegol/jules-verne_from-the-earth-to-the-moon_ward-lock-co#1]
NOTE: it might be worth while to try and semanticate as much as possible before running modernize-spelling… scan for `<i>`, `<abbr>` etc.

Always check Merriam Webster for  other languages. So much has been adopted into English over the last century.

- Mismatched diacritics
  Crédit   (1)   Credit   (2)  
 ───────────────────────────── 
  Léon     (1)   Leon     (1)  
 ───────────────────────────── 
  aërial   (1)   aerial   (1) 

- Build cover src/epub/images/cover.svg
by jules verne. Translated by WARD, LOCK &amp; CO.</title>
by Jules Verne. Translated by Ward, Lock &amp; Co.</title>

- "cannon -> cannons" change should have been marked as [Editorial]

- removing hyphens is considered editorial — changes should have been marked as [Editorial]

**Content.opf**
- in the long description you should mention it contains two texts: _From the Earth to the Moon_ and _Around the Moon_.
- typo in production notes: Project Gutenberg's "The Moon-Yoyage,

**Multiple chapters**: 
- "savant" is in MW (no xml:lang needed)
- "savants" is in MW (no xml:lang needed)
- "casus belli" is in MW (no xml:lang needed)
- "ad hominem" is in MW (no xml:lang needed)

**Chapter 1** 
- "sine qua non" is in MW (no xml:lang needed)
- "début" is in MW (no xml:lang needed): spelled debut
- "naïf" is in MW (no xml:lang needed)

**Chapter 2** 
- Urbi et Orbi — Styles are fine. You are right about the *et* in this case. I would lowercase the et and make a lint-ignore file https://standardebooks.org/manual/1.6.1/single-page#2.3 
- *New-York American* — I think you can assume this was a newspaper. We tag even made-up publications so I would go ahead and add "se:name.publication.newspaper"
- `<i xml:lang="fr">`sang-froid`</i>` is in MW (no xml:lang needed) and spelled "sangfroid"

**Chapter 5** 
- "débris" is in MW (no xml:lang needed): spelled debris

**Chapter 18**: 
- `<h2 epub:type="title">`The Passenger of the Atlanta`</h2>` Name of ship should be <i> even in titles
- very weird typo :-) `<i xml:lang="friends">`savants`</i>`

**Chapter 20**
- "a priori" is in MW (no xml:lang needed)

**Chapter 21**
- "serviettes" is in MW (no xml:lang needed)
- "alter ego" is in MW (no xml:lang needed)

**Chapter 22** 
- "E pluribus unum"

**Chapter 23** 
- "cap-à-pie" is in MW (no xml:lang needed) spelled cap-a-pie

**Chapter 27**
- "Sic transit gloria mundi" is in MW (no xml:lang needed)

**Chapter 28**
- "dénouement" is in MW (no xml:lang needed): spelled denouement

**Comment by b-t-k** [comment]
Remember to run clean, typogrify, semanticate, lint etc. after making big changes —I've made this mistake too many times to count ;-) There are bunch of tiny changes. And you should get in the habit of running clean every time you make any change.

Run `pipx upgrade standardebooks` I think there was a change to fractions in semanticate
Sorry about the _ad hominem_  etc. change. It snuck up on me in the last batch of revisions.

**content.opf**
It is not clear to me in the long description that this edition contains — as you put it in the production notes— "both "From the Earth to the Moon" and its sequel "Around the Moon."  I'd add something similar.

The typo is still in content.opf
- typo in production notes: Project Gutenberg's "The Moon-**Y**oyage,

We don't usually add the reviewers to the content.opf and leave that to Alex. FWIW I usually don't use my first name:
```
		<dc:contributor id="producer-1">B. Timothy Keith</dc:contributor>
		<meta property="file-as" refines="#producer-1">Keith, B. Timothy</meta>
```

**Comment by gsegol** [comment]
Bruce
I had run semanticate, typogrify, clean and lint before resubmitting. No issues in lint, so I really don’t know what errors are still showing up. But I will do it again. 

As for the long description, Alex told me to split the single Gutenberg book—which contains two Jules Verne titles— into two SE books. That is what I was trying to explain. 

Regards 

Genevieve

**Comment by b-t-k** [comment]
Huh. I think the clean and typogrify issues were artifacts on my clone. But lint finds those errors with the italics (my fault) and some bad quotes. Did you update your tools?

And I finally get what's going on with the two books. I had assumed it was the other way around. So that's good as is. Don't forget the typo though. Let me know when those bits are fixed and we are good to go

**Comment by gsegol** [comment]
Bruce,

- I did the pipx upgrade
- I corrected the typo in the production notes (sorry); also changed straight quotes to smart quotes.
- I changed your name as requested.
- I rerun semanticate, typogrify, clean and lint.  And now, I have three t-063 errors: “Latin phrase set without italics”—pointing to “ad hominem” (Ch18 & 22) and "a priori" (Ch20). This is madness =:0

I have not pushed the changes to GitHub until you tell me what to do with the last point.
Thanks.

Geneviėve
***@***.***

**Comment by b-t-k** [comment]
The three t-063 errors are because I made you get rid of the xml lang and italics, but then Alex changed the rules and wants them back in for those particular words. Entirely my fault... sorry about that!  See  [ https://standardebooks.org/manual/1.6.2/single-page#8.9.1.1](https://standardebooks.org/manual/1.6.2/single-page#8.9.1.1) for an explanation.

**Comment by gsegol** [comment]
OK.  I will correct this back.  But for the rest of us, it means that the “MW rule” is no longer valid.  Hard to explain why “Casus belli” is more ‘English’ than “a priori.”  I would argue the opposite.  But c’est la vie!

Geneviėve
***@***.***

**Comment by b-t-k** [comment]
Looks good. 
There's been some discussion about it but it comes down to the "a" being ambiguous in "a priori" and this was the easiest way to distinguish.

Great job!
